HugoByte/polkadot-kurtosis-package

- chopsticks/config.json
- chopsticks/main.star
- package_io/polkadot_js_app.star
```bash
fix: fix chopsticks issue while running xcm service
```
```bash
```
> fix: fix chopsticks issue while running xcm service

- main.star
- package_io/constant.star
- package_io/utils.star
- parachain/parachain.star
- relaychain/relay-chain.star
…node still runs
```bash
fix: fix issue when the node type is anything which is not valid the still node in getting started as full node
```
```bash
If the node-type in local.json is not valid the starlark package execution will fail
```
> fix: fix issue when the node type is anything which is not valid the still node in getting started as full node

- main.star
- package_io/utils.star
Refactored upload files in main.star and added it to utils
```bash
refactor: refactor upload files for parachain
```
> refactor: refactor upload files for parachain

- relaychain/relay-chain.star
Fixed issue for polkadot relay node not running on mac OS
```bash
fix: fix issue for polkadot relay node not running in mac
```
> fix: fix issue for polkadot relay node not running in mac

- main.star
- package_io/promethues.star
Refactored args for launch prometheus
```bash
refactor: refactor args for launch prometheus
```
> refactor: refactor args for launch prometheus

- parachain/node_setup.star
- parachain/parachain.star
- relaychain/relay-chain.star
```bash
fix: parachain bloduce issue in local setup
```
```bash
```
> fix: parachain bloduce issue in local setup

- package_io/constant.star
- parachain/parachain.star
```bash
fix: bifrost local node
```
```bash
```
> fix: bifrost local node

- local.json
- parachain/static_files/images.star
```bash
fix: fix issue running acala, karura, moonbeam local parachain setup
```
```bash
```
> fix: fix issue running acala, karura, moonbeam local parachain setup

- parachain/static_files/images.star
```bash
fix: moonriver block producing issue
```
> fix: moonriver block producing issue

- parachain/node_setup.star
```bash
fix: phala parachain port issue
```
> fix: phala parachain port issue

- testdata/e2e/para_relay.js
- testdata/e2e/relay_para.js
```bash
test: update script to use sdk to send message from para to relay in local net
```
> test: update script to use sdk to send message from para to relay in local net

- README.md
- local.json
- main.star
- package_io/constant.star
- package_io/grafana.star
- package_io/promethues.star
- package_io/utils.star
- parachain/node_setup.star
- parachain/parachain.star
- relaychain/relay-chain.star
- testdata/updated_config.json
Refactored public ports for relay and para chains
```bash
refactor: refactor public ports for relay and para chains
```
> refactor: refactor public ports for relay and para chains

- testdata/generate_json.py
```bash
test: update test script to handle new changes in config.json
```
> test: update test script to handle new changes in config.json

- parachain/node_setup.star
fixed port key
```bash
fix: port key fix
```
> fix: port key fix

- chopsticks/chopstick.star
- main.star
- package_io/build-spec.star
- package_io/chopsticks.star
- package_io/polkadot_js_app.star
- parachain/node_setup.star
- parachain/parachain.star
- relaychain/relay-chain.star
```bash
fix: doc-string in package
```
> fix: doc-string in package

- package_io/constant.star
- parachain/parachain.star
Removed ws port list for para chains
```bash
chore: remove ws port for parachains
```
> chore: remove ws port for parachains

- README.md
- package_io/constant.star
remove integritee from ws port list
```bash
fix: remove integritee from ws port list
```
```bash
```
> fix: remove integritee from ws port list

- .github/workflows/local.yaml
- testdata/generate_json.py
```bash
fix: localnet github workflow action
```
> fix: localnet github workflow action

- package_io/polkadot_js_app.star
olkadot-js-apps port name key
```bash
fix: polkadot-js-apps port name
```
> fix: polkadot-js-apps port name

- parachain/parachain.star
- parachain/register-para-id.star
```bash
fix: parachain artifact name conflict
```
> fix: parachain artifact name conflict

- package_io/constant.star
- parachain/parachain.star
- parachain/static_files/images.star
```bash
fix: fix issue for robonomics, litentry, acala, karura, kilt testnet issues
```
```bash
```
> fix: fix issue for robonomics, litentry, acala, karura, kilt testnet issues
